### ISSUE TITLE
Safeguarding Guatemala's elections documents using OpenTimestamps

### ISSUE THREAD

**Issue by rafacorcof** [TABConf/2023.tabconf.com#132] opened 2023-08-14 16:36 UTC
# Description
### What is this talk about? Give us as many details as possible. 
There is a growing global trend of attacks on elections in many democracies from individuals and organizations looking to undermine the legitimacy of the electoral process. These attacks are carried out through misinformation campaigns, fake news and false claims of fraud among others. In order to safeguard the 2023 elections documents, Guatemala's Supreme Elections Tribunal (TSE) implemented an "Immutable Backup" solution for the official vote tally sheet images. The Immutable Backup includes automatically storing the hash of the documents in the Bitcoin blockchain in near real-time as they are digitized. This solution was developed by a startup called Simple Proof and uses the open source OpenTimestamps protocol. Rafa Cordon, CEO/Founder of Simple Proof speaks about how the solution was proposed to the customer, how it was implemented and how Simple Proof can help increase transparency and security of public documents produced by governments. Peter Todd, the inventor of OpenTimestamps speaks about how he created the protocol, other use cases and innovations he sees across the world and how he collaborated with Simple Proof on implementing their solution.

### What would an attendee learn from this talk? 
An attendee would learn about a use case of Bitcoin for a non-currency application, specifically how the OpenTimestamps protocol enables reliable, scalable timestamping and how other types of applications such as Simple Proof build on top of this protocol. Also the attendee will learn about how Bitcoin can be applied in the public sector for non-currency applications.
### Is there anything folks should read up on before they attend this talk?
They can read the OpenTimestamps website, the Simple Proof website and watch a podcast that Rafa and Peter recorded.

### Relevant Links
Simple Proof website (coming in English soon): https://simpleproof.com/
OpenTimestamps website: https://opentimestamps.org/
Conversation between Rafa and Peter about OpenTimestamps: https://youtu.be/LR4WhCjHkq4

# About the Speakers
### Social Links
Rafa Cordon
Github: https://github.com/rafacorcof
Twitter: https://twitter.com/Rafa_Cordon
Website: https://itzdata.tech/en/

Peter Todd
Github: https://github.com/peterrtodd
Twitter: https://twitter.com/peterktodd
Website: https://petertodd.org/

# Talk Details
### Length of Talk
30 minutes + 10 minutes Q&A
### Preferred Day/Time Slot 
No preference
*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by petertodd** [comment] 2023-08-14 17:15
> NOTE: @petertodd and I discussed proposing this presentation and he's onboard. He mentioned that he's happy to accommodate for this talk in case he has already been approved for other presentations.

Confirmed. Notably, this may be a more interesting topic for the conference than full-RBF and if time is an issue, I'd be happy to do this instead of that.

**Comment by petertodd** [comment] 2023-08-14 17:16
> NOTE: @petertodd and I discussed proposing this presentation and he's onboard. He mentioned that he's happy to accommodate for this talk in case he has already been approved for other presentations.

Confirmed. Notably, this may be a more interesting topic for the conference than full-RBF and if time is an issue, I'd be happy to do this instead of that.

**Comment by iglesiasbrandon** [comment] 2023-08-15 12:28
Thank you, @rafacorcof & @petertodd I will discuss this with the organizers and get back to you all.

**Comment by iglesiasbrandon** [comment] 2023-08-17 11:10
Hey @petertodd & @rafacorcof we are going to swap this issue for #15 on the main stage. 

We have added a day, time slot, and length to this issue. We can only allocate 25 minutes in total. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by rafacorcof** [comment] 2023-08-17 12:06
ack

**Comment by petertodd** [comment] 2023-08-28 20:55
ACK

**Comment by iglesiasbrandon** [comment] 2023-09-09 22:12
Closing this issue because it's been completed!

**Closed by iglesiasbrandon** 2023-09-09 22:12 UTC
Labels: Talk, Accepted, ACK
