### ISSUE TITLE
Understanding Ark

### ISSUE THREAD

**Issue by stevenroose** [TABConf/2023.tabconf.com#90] opened 2023-07-05 20:29 UTC
# Description
### What is this talk about? Give us as many details as possible. 

A technical explanation of Ark. Instead of starting with why the world needs Ark, this talk is a technical explanation of Ark that construction the concepts involved from the ground up.

### What would an attendee learn from this talk?
Most things about Ark. How it works and ideally how to build it.
### Is there anything folks should read up on before they attend this talk?
No.

### Relevant Links
- https://roose.io/presentations
- https://arkpill.me

# About the Speaker

Bitcoin developer since 2012. Currently active at rust-bitcoin. Worked in the Liquid team at Blockstream the last 4.5 years. Before that worked on various small things, a.o. btcd.

### Social Links
Github: https://github.com/stevenroose
Mastodon: https://x0f.org/@stevenroose

# Talk Details
### Length of Talk
Working on it. Give me a slot, I guess 1h would be good. Could try 30m.
### Preferred Day/Time Slot 
flexible

**Comment by supertestnet** [comment] 2023-07-10 20:08
Steven Roose was one of three people selected by Buraq to join him in San Francisco to iron out the details of Ark and begin work on an implementation. The other two were myself and Robin Linus. I can confirm that Steven is intimately familiar with the details of Ark, and has even made some progress on an implementation for signet. I think he is a wonderful choice to present the latest ideation of it.

**Comment by iglesiasbrandon** [comment] 2023-07-14 16:15
Hey @stevenroose thank you for submitting this issue! Would this be better suited as a workshop instead of a talk? 
Could you also add some more detail to the description?

**Comment by stevenroose** [comment] 2023-07-14 19:39
Because it's titled Building an Ark? I don't really consider it a workshop. It's a talk that explains Ark, but instead of starting from the "why we need Ark and why will it rule the world" angle, it starts from the ground up explaining what it is and how it works. I'll add that to the description. Maybe "Understanding Ark" would be a better title?

**Comment by basyeks** [comment] 2023-07-17 00:50
hey

**Comment by miketwenty1** [comment] 2023-07-17 01:23
@basyeks 

> hey

We will look into this on Wednesday when we do another round of accepting.

**Comment by stevenroose** [comment] 2023-07-24 19:54
Any news? I need to start planning my trip etc and I probably won't come if I'm not speaking. Also, I just did my talk to a coworker and he understands all aspects of Ark now :sunglasses:

**Comment by iglesiasbrandon** [comment] 2023-07-25 11:39
Hey @stevenroose, congratulations, this issue has been accepted for TABConf 2023!

It's been added to the official [GitHub Project schedule](https://github.com/orgs/TABConf/projects/1/views/2).
The talks will be happening on September 8th and 9th; once we accept more, we will assign the day, time, and location.

**Comment by iglesiasbrandon** [comment] 2023-08-17 11:03
Hey @stevenroose , We have added a day, time slot, and length to this issue. 
You can find it on the schedule in this view: https://github.com/orgs/TABConf/projects/1/views/6

Please acknowledge by commenting 'ack'.

This will confirm your talk for TABConf 2023!
If we need to make any changes, you will be notified on this issue.

**Comment by stevenroose** [comment] 2023-08-18 02:37
ACK :)

**Comment by iglesiasbrandon** [comment] 2023-09-08 20:53
Closing this issue since it's been completed!

**Closed** 2023-09-08 20:53 UTC
Labels: Talk, Accepted, ACK
