### ISSUE TITLE
SeedSigner: Worldwide v0.7.0 debut 🎉, Reproducible Build demo 🔥, Q&A w/the team

### ISSUE THREAD

**Issue by kdmukai** [TABConf/2023.tabconf.com#180] opened 2023-08-31 13:57 UTC
# Description
### What is this workshop about? Provide as many details as possible. 

The core SeedSigner team: @seedsigner, @newtonick, and @kdmukai will be at TABConf for the worldwide debut of our MASSIVE v0.7.0 release which includes reproducible builds!

We'll do a live reproducible build w/attendees optionally following along themselves on their laptops.

We'll demo the major enhancements and new features in v0.7.0.

Will include a open Q&A session and discussion throughout.

Interested attendees can follow up with @seedsigner if they want to buy a SeedSigner kit from him.

### What would an attendee learn from this workshop?

* How to access and begin leveraging the new v0.7.0 release
* How to do a SeedSigner reproducible build, why that matters, what assurances that does -- and does not -- offer.
* Who the core SeedSigner team is w/direct Q&A w/all three of us.

### Is there anything attendees should read up on before they attend this talk?

No, presumably attendees will self-select on their existing interest either in SeedSigner in general or in reproducible builds.

### Is there anything attendees should set up before the workshop?

If they want to do the reproducible build, bring a laptop w/a hotspot. Or begin following the steps [in the SeedSigner OS repo](https://github.com/SeedSigner/seedsigner-os) to pre-fetch all the dependencies.

Also consider bringing a SeedSigner, if they've already built one, to run the resulting build image.

### Relevant Links

# About the Speaker
### Social Links
Github: https://github.com/SeedSigner/seedsigner
Twitter: https://twitter.com/SeedSigner, https://twitter.com/newtonick, https://twitter.com/KeithMukai
Website: seedsigner.com

# Workshop Details
### Length of workshop
1 hr

### Preferred Day/Time Slot 
Day 3 preferred (maximize the SeedSigner pleb general attendance), whenever and in whichever room is available!

Nick will NOT be there on Day 4.

Day 1 or 2 possible, but less desirable.

*We will do our best to accommodate your requested time slot. Please let us know if there are any dates/times that ***absolutely do not work*** for you.*

**Comment by miketwenty1** [comment] 2023-09-01 00:48
@iglesiasbrandon Keith is suggesting this be on Day 3.. I'm guessing in a break out room.

I also see seedsigner has a builders day table..
https://github.com/TABConf/2023.tabconf.com/issues/71

But this looks like a completely separate thing?.. if this is run on day3.. would it make sense to run in the evening when there aren't many events going on in it's own room or should it happen through something like base58 village as an activity? (granted they/lisa is ok with that). Just brainstorming.

**Comment by kdmukai** [comment] 2023-09-01 00:51
@miketwenty1 yeah, Builder's Day table will just be open to talk to us, check out a SeedSigner, discuss possible new features, peruse the code, etc.

The workshop proposed here will be a guided activity + presentation + discussion.

**Comment by miketwenty1** [comment] 2023-09-02 03:18
@kdmukai I'm almost wondering if it would make more sense to do this day 1 or 2.. in case we get a drop out.. or we just extend the schedule for people who want to keep hacking.. you think there would be any appetite for late evening seed signing after dinner? (granted hotel = venue)

**Comment by kdmukai** [comment] 2023-09-02 13:27
@miketwenty1 what considerations are you trying to juggle?

I should also clarify: though the reproducible build workshop is a highlight, it should really only be a couple of setup steps and then about 25min of it running in the background just doing its own thing. So the majority of the time will really be about demoing the v0.7.0 release and the Q+A.

So maybe I shouldn't even say "Workshop" in the title. It really is meant for just casual SeedSigner enthusiasts who want to learn more about v0.7.0. Not hard core devs.

Anyway, that's why I was thinking Day 3 since I'm not sure if the less technical folks (relatively speaking for this conf!) will be there for Day 1 or Day 2.

If the concern is about overlapping on existing presentations, 4:30 on Day 3 probably has a totally different audience for the Main Stage. Hopefully Nifty or the BitDevs room would be okay hosting us.

**Comment by kdmukai** [comment] 2023-09-06 14:17
Hola, @vnprc!

**Comment by btsea** [comment] 2023-09-08 00:41
Hi @kdmukai, we carved out a slot for you tomorrow. Please keep it to 45 minutes; hopefully that is enough. We ask that you start and finish promptly. Thank you.

**Comment by btsea** [comment] 2023-09-08 00:45
@SeedSigner, @newtonick please ACK this so I can assign the issue to you. Thank you!

**Comment by SeedSigner** [comment] 2023-09-08 00:46
ACK -- TY!

**Comment by newtonick** [comment] 2023-09-08 01:00
ACK

**Comment by btsea** [comment] 2023-09-08 17:59
Thanks guys, congrats on the reproducible build!! @newtonick @SeedSigner @newtonick 

Closing now that the event is complete.

**Closed by btsea** 2023-09-08 17:59 UTC
Labels: Workshop, Accepted, ACK
